---
title: "A3_Q1"
author: "Joohyeok"
date: "2024-03-06"
output: html_document
---

```{r setup, include=TRUE}
library(readxl) 
library(ggplot2)
library(GGally)
library(dplyr)
library(tidyverse)
library(corrplot)

X <- read_excel("NationalParks.xlsx")
X

```

a)  Present a matrix scatter plot.
```{r}
ggpairs(X[,-1], lower=list(continuous = wrap("points", color = "blue")))+
  theme_bw()+
  theme(strip.text=element_text(size=12))

```

b)  Compute and display the sample correlation matrix.
```{r}
numericData <- X[sapply(X, is.numeric)]

cor(numericData, use = "complete.obs") 

```


d) Produce a new data set by removing the data for the unusual park. Present a
matrix scatter plot from the new data
```{r}
new_X <- X[-c(7), ]

new_X

ggpairs(new_X[,-1], lower=list(continuous = wrap("points", color = "blue")))+
  theme_bw()+
  theme(strip.text=element_text(size=12))

```

e) Compute the sample correlation matrix for the new data set
```{r}
new_numericData <- new_X[sapply(new_X, is.numeric)]

cor(new_numericData, use = "complete.obs") 

```



