---
title: "A4_Q1"
author: "Joohyeok"
date: "2024-03-13"
output: html_document
---

```{r setup, include=TRUE}
library(readxl) 
library(ggplot2)
library(GGally)
library(dplyr)
library(tidyverse)
library(corrplot)
library(reshape2)
library(readr)
library(stats)


data <- read.table("paper_mill_data_response.txt",skip=1,sep="\t",header=FALSE)
```

a) Label the variables r1, · · · , r13. Carry out an initial investigation
```{r}
colnames(data) <- c(paste0("r", 1:13))

head(data)

summary(data)
sapply(data, sd)
 sapply(data, function(x) sum(is.na(x)))
```

b) Display the sample correlation matrix R
```{r}
cor(data)

```

c) (i) List the eigenvalues and describe the percent contributions to the variance
```{r}
result <- prcomp(data, scale. = TRUE)

eigenvalues <- result$sdev^2

percent_variance <- eigenvalues / sum(eigenvalues) * 100
eigenvalues
percent_variance

```

(ii) scree plot
```{r}
plot(eigenvalues, type = "b", pch = 19, frame = FALSE, 
     xlab = "Principal Component", ylab = "Eigenvalue", 
     main = "Scree Plot")
abline(h = 1, col = "red", lty = 2)
```

(iii) Give the eigenvectors for the first two principal components
```{r}
eigenvectors <- result$rotation[, 1:2]
print(eigenvectors)

```

(v) Display a scatter plot of the first two principal components
```{r}
result
plot(result$x[, 1], result$x[, 2], xlab="First Principal Component", ylab="Second Principal Component")

```

