---
title: "A3_Q2"
author: "Joohyeok"
date: "2024-03-08"
output: html_document
---

```{r setup, include=TRUE}
library(readxl) 
library(ggplot2)
library(GGally)
library(dplyr)
library(tidyverse)
library(corrplot)
library(reshape2)
library(readr)

data <- read_excel("survival_data.xlsx",
                col_names = c("Group", "B", "C", "D", "E", "F"))

```

a) Display a boxplot of the data
```{r}
boxplot(data[, -1], col = c("red","orange","yellow","blue","pink"),
        xlab="Variables", ylab="Values", names=c("B", "C", "D", "E", "F"))

```

b) Display a matrix scatter plot
```{r}
Color<-as.factor(data$Group)
colors <- c("yellow","blue","cyan","pink","brown")

data %>%
  mutate(Color = factor(Color)) %>%
  ggpairs(columns = 2:6, aes(color = Color),legend=4,
          diag = list(continuous = "barDiag")) +
  theme_bw() +
  theme(plot.title=element_text(hjust=0.5))+
  scale_color_manual(values = colors, labels = c("1", "2", "3", "4", "5"),
                        name = "Color")

```

c) Compute the sample mean vector and standard deviations across all groups, display
```{r}
data %>% group_by(Group) %>%
  summarise(mean_B=mean(B), sd_B=sd(B), mean_C=mean(C), sd_C=sd(C), 
            mean_D=mean(D), sd_D=sd(D), mean_E=mean(E), sd_E=sd(E), 
            mean_F=mean(F), sd_F=sd(F))

```

d) Compute the matrix of sample means within groups using the standardized values, display
```{r}
stand <- function(x) {
  (x - mean(x)) / sd(x)
}

mean_value<-data %>% 
  mutate(across(B:F, stand)) %>%
  group_by(Group) %>%
  summarise(mean_B=mean(B), mean_C=mean(C),
            mean_D=mean(D), mean_E=mean(E),
            mean_F=mean(F))
mean_value

```

e) Compute the distance matrix between the groups using the standardized values, display.
```{r}
distance_matrix <- as.dist(dist(mean_value[,-1]))

as.matrix(distance_matrix)

```





